### ISSUE TITLE
NavBar Component

### ISSUE THREAD

**Issue by hpar461** [SE701-T5/Frontend#17]
- Has a dropdown for all the different communities of a user which shows only if a user is logged in
- Can search for specific posts or communities based on a search filter users can select from a dropdown
  - If user clicks a search icon, it begins search with the current keyword in the search box.
- Button to create a new post
  - If user is not logged in it will redirect them to the Login page
  - If user is logged in it will redirect them to New Post page
- Button to create a new community
  - If user is not logged in it will redirect them to the Login page
  - If user is logged in it will redirect them to New Community page
- If user is logged in button for dropdown menu with these options:
  - Profile
  - Logout
- if user is not logged in display a login button and register button that redirects to specified pages

**Comment by yuchendong13** [comment]
Looks amazing Hyung! I'm not sure if it's a feature to be added later, but I'm wondering if the search icon should be a button?

**Comment by hpar461** [comment]
> Looks amazing Hyung! I'm not sure if it's a feature to be added later, but I'm wondering if the search icon should be a button?

Hmm... Right, so when i press search icon, it would search with the current keyword in the search bar. Will include that in the feature list above and try to implement it when we implement navigation in the nav bar!
