### ISSUE TITLE
Wireframing / Feature Planning

### ISSUE THREAD

**Issue by Tvo465** [SE701-T5/Frontend#6]
Designing the layout of the website.

**Comment by christopher-alba** [comment]
# Current State of Designs
To view our designs click the following link: 
https://www.figma.com/file/iYVrT2brMo15dMULpfXqEk/YCD_Basic_Design_Idea?node-id=0%3A1

# Reusable Components
### Post preview component 
![image](https://user-images.githubusercontent.com/58793979/158040928-204e019b-9f6c-4fb3-8178-bcdbc284093c.png)
- reused in homepage, post page, communities page
- contains the community name
- contains timestamp of the post and who posted it
- contains title of the post
- contains description of the post that's cut off at specific character length by ellipsis 
- contains upvote/downvote buttons with a number in the middle that represents #upvotes - #downvotes
- contains comment button with floating label for number of comments 
- may contain image/image slider (multiple images)

# Navbar Features / Gotchas 
- Has a dropdown for all the different communities of a user which shows only if a user is logged in
- Can search for specific posts or communities based on a search filter users can select from a dropdown
- Button to create a new post 
  * If user is not logged in it will redirect them to the **Login** page
  * If user is logged in it will redirect them to **New Post** page
- Button to create a new community
  * If user is not logged in it will redirect them to the **Login** page
  * If user is logged in it will redirect them to **New Community** page
- If user is logged in button for dropdown menu with these options: 
  * Profile
  * Logout
- if user is not logged in display a login button and register button that redirects to specified pages

# Pages
### Homepage 
- popular communities section that's horizontally scrollable via dragging by the mouse
- popular posts section 
 * ordered by highest net voting score

### Post 
- Contains the full post details
- contains comments view
  * comments can have upvotes and downvotes and a number that shows the net value
  * comments are filtered by popularity (net value)
  * comments can be deleted by the user that created them
### Community 
- contains a background picture (changeable only by the person who created it)
- contains a join button for non-members 
- contains a leave button for members
- contains a post button for members
- contains a delete button for creator/admins of the community
- contains a member count and you can click and view all the different member's names
- contains a description of the community
- contains a list of all community's posts ordered by latest timestamp first
### New Post 
- contains text box for title
- contains dropdown to select forum the post is for
- contains text area for post description
- contains upload media button for pictures
### New Community
- contains text box for community name
- contains text area for community description
- able to upload image for community background
- able to see the image that was uploaded and delete it if necessary
### Login 
- login using username/email and password
- redirect button to register

### Register 
- register using email/ username/password
- redirect button to register

### Posts 
- contains a list of all the posts
- contains a searchbar to search all the posts

### Communities
- contains a list of all the communities
- contains a searchbar to search all the communities

**Comment by christopher-alba** [comment]
This marks the last day that team5 will be contributing to this repository in terms of code contributions.
